=begin
#giphy-api

#Giphy's public api.

OpenAPI spec version: 0.9.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'GiphyClient/api_client'
require 'GiphyClient/api_error'
require 'GiphyClient/version'
require 'GiphyClient/configuration'

# Models
require 'GiphyClient/models/base_channel_model'
require 'GiphyClient/models/base_channel_model_gifs'
require 'GiphyClient/models/breadcrumb'
require 'GiphyClient/models/category'
require 'GiphyClient/models/channel_with_children_model'
require 'GiphyClient/models/channel_with_children_model_children'
require 'GiphyClient/models/gif'
require 'GiphyClient/models/gif_images'
require 'GiphyClient/models/gif_images_downsized'
require 'GiphyClient/models/gif_images_downsized_large'
require 'GiphyClient/models/gif_images_downsized_medium'
require 'GiphyClient/models/gif_images_downsized_small'
require 'GiphyClient/models/gif_images_downsized_still'
require 'GiphyClient/models/gif_images_fixed_height'
require 'GiphyClient/models/gif_images_fixed_height_downsampled'
require 'GiphyClient/models/gif_images_fixed_height_small'
require 'GiphyClient/models/gif_images_fixed_height_small_still'
require 'GiphyClient/models/gif_images_fixed_height_still'
require 'GiphyClient/models/gif_images_fixed_width'
require 'GiphyClient/models/gif_images_fixed_width_downsampled'
require 'GiphyClient/models/gif_images_fixed_width_small'
require 'GiphyClient/models/gif_images_fixed_width_small_still'
require 'GiphyClient/models/gif_images_fixed_width_still'
require 'GiphyClient/models/gif_images_looping'
require 'GiphyClient/models/gif_images_original'
require 'GiphyClient/models/gif_images_original_still'
require 'GiphyClient/models/gif_images_preview'
require 'GiphyClient/models/gif_images_preview_gif'
require 'GiphyClient/models/inline_response_200'
require 'GiphyClient/models/inline_response_200_1'
require 'GiphyClient/models/inline_response_200_2'
require 'GiphyClient/models/inline_response_200_3'
require 'GiphyClient/models/inline_response_200_4'
require 'GiphyClient/models/inline_response_200_5'
require 'GiphyClient/models/inline_response_400'
require 'GiphyClient/models/last_child_model'
require 'GiphyClient/models/last_child_model_children'
require 'GiphyClient/models/meta_content'
require 'GiphyClient/models/meta_object'
require 'GiphyClient/models/pagination'
require 'GiphyClient/models/random_gif'
require 'GiphyClient/models/shallow_tag'
require 'GiphyClient/models/tag'
require 'GiphyClient/models/trending_tag'
require 'GiphyClient/models/user'

# APIs
require 'GiphyClient/api/default_api'

module GiphyClient
  class << self
    # Customize default settings for the SDK using block.
    #   GiphyClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
